/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: src/linear_solver/python/linear_solver.swig

package ilp

/*
#cgo CXXFLAGS: -std=c++0x -fwrapv -O4 -DNDEBUG -I/home/bpowers/src/or-tools/src -I/home/bpowers/src/or-tools/examples -I/home/bpowers/src/or-tools/src/gen -I/home/bpowers/src/or-tools/dependencies/install/include -DARCH_K8 -Wno-deprecated -I/home/bpowers/src/or-tools/dependencies/install/include -I/home/bpowers/src/or-tools/dependencies/install/include -DUSE_CBC -I/home/bpowers/src/or-tools/dependencies/install/include -DUSE_CLP      -DUSE_GLOP -DUSE_BOP -I/home/bpowers/src/or-tools/dependencies/install/include
#cgo LDFLAGS: -L/home/bpowers/src/or-tools/lib -lortools -lrt -lpthread

#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_ilp_70c2f4f52bc62623(swig_intgo arg1);
extern swig_intgo _wrap_CLP_LINEAR_PROGRAMMING_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_GLOP_LINEAR_PROGRAMMING_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_CBC_MIXED_INTEGER_PROGRAMMING_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_BOP_INTEGER_PROGRAMMING_Solver_ilp_70c2f4f52bc62623(void);
extern uintptr_t _wrap_new_Solver_ilp_70c2f4f52bc62623(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_delete_Solver_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern _Bool _wrap_Solver_SupportsProblemType_ilp_70c2f4f52bc62623(swig_intgo arg1);
extern void _wrap_Solver_Clear_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern swig_intgo _wrap_Solver_NumVariables_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern uintptr_t _wrap_Solver_LookupVariable_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Solver_NumVar_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2, double arg3, uintptr_t arg4);
extern uintptr_t _wrap_Solver_IntVar_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2, double arg3, uintptr_t arg4);
extern uintptr_t _wrap_Solver_BoolVar_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_Solver_NumConstraints_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern uintptr_t _wrap_Solver_LookupConstraint_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Solver_Constraint__SWIG_0_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2, double arg3);
extern uintptr_t _wrap_Solver_Constraint__SWIG_1_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern uintptr_t _wrap_Solver_Constraint__SWIG_2_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2, double arg3, uintptr_t arg4);
extern uintptr_t _wrap_Solver_Constraint__SWIG_3_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Solver_Objective_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern swig_intgo _wrap_OPTIMAL_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_FEASIBLE_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_INFEASIBLE_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_UNBOUNDED_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_ABNORMAL_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_NOT_SOLVED_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_Solver_Solve__SWIG_0_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern swig_intgo _wrap_Solver_Solve__SWIG_1_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Solver_ComputeConstraintActivities_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern _Bool _wrap_Solver_VerifySolution_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2, _Bool arg3);
extern _Bool _wrap_Solver_InterruptSolve_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern _Bool _wrap_Solver_SetSolverSpecificParametersAsString_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_FREE_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_AT_LOWER_BOUND_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_AT_UPPER_BOUND_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_FIXED_VALUE_Solver_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_BASIC_Solver_ilp_70c2f4f52bc62623(void);
extern double _wrap_Solver_infinity_ilp_70c2f4f52bc62623(void);
extern void _wrap_Solver_EnableOutput_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_Solver_SuppressOutput_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_Solver_set_time_limit_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Solver_wall_time_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern uintptr_t _wrap_Solver_iterations_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern uintptr_t _wrap_Solver_nodes_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern double _wrap_Solver_ComputeExactConditionNumber_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern uintptr_t _wrap_Solver_ExportModelAsLpFormat_ilp_70c2f4f52bc62623(uintptr_t arg1, _Bool arg2);
extern uintptr_t _wrap_Solver_ExportModelAsMpsFormat_ilp_70c2f4f52bc62623(uintptr_t arg1, _Bool arg2, _Bool arg3);
extern uintptr_t _wrap_Solver_LoadModelFromProto_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_Solver_SetTimeLimit_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Solver_WallTime_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_Objective_Clear_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_Objective_SetCoefficient_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2, double arg3);
extern double _wrap_Objective_GetCoefficient_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_Objective_SetOffset_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2);
extern double _wrap_Objective_offset_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_Objective_AddOffset_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2);
extern void _wrap_Objective_SetOptimizationDirection_ilp_70c2f4f52bc62623(uintptr_t arg1, _Bool arg2);
extern void _wrap_Objective_SetMinimization_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_Objective_SetMaximization_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern _Bool _wrap_Objective_maximization_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern _Bool _wrap_Objective_minimization_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern double _wrap_Objective_Value_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern double _wrap_Objective_BestBound_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_delete_Objective_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern uintptr_t _wrap_Variable_name_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern _Bool _wrap_Variable_integer_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern double _wrap_Variable_solution_value_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern swig_intgo _wrap_Variable_index_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern double _wrap_Variable_lb_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern double _wrap_Variable_ub_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern double _wrap_Variable_reduced_cost_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern swig_intgo _wrap_Variable_basis_status_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern uintptr_t _wrap_Variable___str___ilp_70c2f4f52bc62623(uintptr_t arg1);
extern uintptr_t _wrap_Variable___repr___ilp_70c2f4f52bc62623(uintptr_t arg1);
extern double _wrap_Variable_SolutionValue_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_Variable_SetLb_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2);
extern void _wrap_Variable_SetUb_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2);
extern double _wrap_Variable_ReducedCost_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_delete_Variable_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern uintptr_t _wrap_Constraint_name_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_Constraint_SetCoefficient_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2, double arg3);
extern double _wrap_Constraint_GetCoefficient_ilp_70c2f4f52bc62623(uintptr_t arg1, uintptr_t arg2);
extern double _wrap_Constraint_lb_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern double _wrap_Constraint_ub_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_Constraint_SetLB_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2);
extern void _wrap_Constraint_SetUB_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2);
extern void _wrap_Constraint_SetBounds_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2, double arg3);
extern void _wrap_Constraint_set_is_lazy_ilp_70c2f4f52bc62623(uintptr_t arg1, _Bool arg2);
extern swig_intgo _wrap_Constraint_index_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern double _wrap_Constraint_dual_value_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern swig_intgo _wrap_Constraint_basis_status_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_Constraint_SetLb_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2);
extern void _wrap_Constraint_SetUb_ilp_70c2f4f52bc62623(uintptr_t arg1, double arg2);
extern double _wrap_Constraint_DualValue_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern void _wrap_delete_Constraint_ilp_70c2f4f52bc62623(uintptr_t arg1);
extern swig_intgo _wrap_RELATIVE_MIP_GAP_MPSolverParameters_ilp_70c2f4f52bc62623(void);
extern swig_intgo _wrap_PRESOLVE_MPSolverParameters_ilp_70c2f4f52bc62623(void);
extern double _wrap_MPSolverParameters_kDefaultPrimalTolerance_get_ilp_70c2f4f52bc62623(void);
extern uintptr_t _wrap_new_MPSolverParameters_ilp_70c2f4f52bc62623(void);
extern void _wrap_MPSolverParameters_SetDoubleParam_ilp_70c2f4f52bc62623(uintptr_t arg1, swig_intgo arg2, double arg3);
extern void _wrap_MPSolverParameters_SetIntegerParam_ilp_70c2f4f52bc62623(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3);
extern double _wrap_MPSolverParameters_GetDoubleParam_ilp_70c2f4f52bc62623(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_MPSolverParameters_GetIntegerParam_ilp_70c2f4f52bc62623(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_delete_MPSolverParameters_ilp_70c2f4f52bc62623(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_ilp_70c2f4f52bc62623(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrSolver uintptr

func (p SwigcptrSolver) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSolver) SwigIsSolver() {
}

type Operations_researchMPSolverOptimizationProblemType int

func _swig_getSolver_CLP_LINEAR_PROGRAMMING_Solver() (_swig_ret Operations_researchMPSolverOptimizationProblemType) {
	var swig_r Operations_researchMPSolverOptimizationProblemType
	swig_r = (Operations_researchMPSolverOptimizationProblemType)(C._wrap_CLP_LINEAR_PROGRAMMING_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverCLP_LINEAR_PROGRAMMING Operations_researchMPSolverOptimizationProblemType = _swig_getSolver_CLP_LINEAR_PROGRAMMING_Solver()

func _swig_getSolver_GLOP_LINEAR_PROGRAMMING_Solver() (_swig_ret Operations_researchMPSolverOptimizationProblemType) {
	var swig_r Operations_researchMPSolverOptimizationProblemType
	swig_r = (Operations_researchMPSolverOptimizationProblemType)(C._wrap_GLOP_LINEAR_PROGRAMMING_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverGLOP_LINEAR_PROGRAMMING Operations_researchMPSolverOptimizationProblemType = _swig_getSolver_GLOP_LINEAR_PROGRAMMING_Solver()

func _swig_getSolver_CBC_MIXED_INTEGER_PROGRAMMING_Solver() (_swig_ret Operations_researchMPSolverOptimizationProblemType) {
	var swig_r Operations_researchMPSolverOptimizationProblemType
	swig_r = (Operations_researchMPSolverOptimizationProblemType)(C._wrap_CBC_MIXED_INTEGER_PROGRAMMING_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverCBC_MIXED_INTEGER_PROGRAMMING Operations_researchMPSolverOptimizationProblemType = _swig_getSolver_CBC_MIXED_INTEGER_PROGRAMMING_Solver()

func _swig_getSolver_BOP_INTEGER_PROGRAMMING_Solver() (_swig_ret Operations_researchMPSolverOptimizationProblemType) {
	var swig_r Operations_researchMPSolverOptimizationProblemType
	swig_r = (Operations_researchMPSolverOptimizationProblemType)(C._wrap_BOP_INTEGER_PROGRAMMING_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverBOP_INTEGER_PROGRAMMING Operations_researchMPSolverOptimizationProblemType = _swig_getSolver_BOP_INTEGER_PROGRAMMING_Solver()

func NewSolver(arg1 Std_string, arg2 Operations_researchMPSolverOptimizationProblemType) (_swig_ret Solver) {
	var swig_r Solver
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Solver)(SwigcptrSolver(C._wrap_new_Solver_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func DeleteSolver(arg1 Solver) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Solver_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

func SolverSupportsProblemType(arg1 Operations_researchMPSolverOptimizationProblemType) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Solver_SupportsProblemType_ilp_70c2f4f52bc62623(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSolver) Clear() {
	_swig_i_0 := arg1
	C._wrap_Solver_Clear_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrSolver) NumVariables() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Solver_NumVariables_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSolver) LookupVariable(arg2 Std_string) (_swig_ret Variable) {
	var swig_r Variable
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Variable)(SwigcptrVariable(C._wrap_Solver_LookupVariable_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrSolver) NumVar(arg2 float64, arg3 float64, arg4 Std_string) (_swig_ret Variable) {
	var swig_r Variable
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Variable)(SwigcptrVariable(C._wrap_Solver_NumVar_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func (arg1 SwigcptrSolver) IntVar(arg2 float64, arg3 float64, arg4 Std_string) (_swig_ret Variable) {
	var swig_r Variable
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Variable)(SwigcptrVariable(C._wrap_Solver_IntVar_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func (arg1 SwigcptrSolver) BoolVar(arg2 Std_string) (_swig_ret Variable) {
	var swig_r Variable
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Variable)(SwigcptrVariable(C._wrap_Solver_BoolVar_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrSolver) NumConstraints() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Solver_NumConstraints_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSolver) LookupConstraint(arg2 Std_string) (_swig_ret Constraint) {
	var swig_r Constraint
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Constraint)(SwigcptrConstraint(C._wrap_Solver_LookupConstraint_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrSolver) Constraint__SWIG_0(arg2 float64, arg3 float64) (_swig_ret Constraint) {
	var swig_r Constraint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Constraint)(SwigcptrConstraint(C._wrap_Solver_Constraint__SWIG_0_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2))))
	return swig_r
}

func (arg1 SwigcptrSolver) Constraint__SWIG_1() (_swig_ret Constraint) {
	var swig_r Constraint
	_swig_i_0 := arg1
	swig_r = (Constraint)(SwigcptrConstraint(C._wrap_Solver_Constraint__SWIG_1_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSolver) Constraint__SWIG_2(arg2 float64, arg3 float64, arg4 Std_string) (_swig_ret Constraint) {
	var swig_r Constraint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Constraint)(SwigcptrConstraint(C._wrap_Solver_Constraint__SWIG_2_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func (arg1 SwigcptrSolver) Constraint__SWIG_3(arg2 Std_string) (_swig_ret Constraint) {
	var swig_r Constraint
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Constraint)(SwigcptrConstraint(C._wrap_Solver_Constraint__SWIG_3_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (p SwigcptrSolver) Constraint(a ...interface{}) Constraint {
	argc := len(a)
	if argc == 0 {
		return p.Constraint__SWIG_1()
	}
	if argc == 1 {
		return p.Constraint__SWIG_3(a[0].(Std_string))
	}
	if argc == 2 {
		return p.Constraint__SWIG_0(a[0].(float64), a[1].(float64))
	}
	if argc == 3 {
		return p.Constraint__SWIG_2(a[0].(float64), a[1].(float64), a[2].(Std_string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrSolver) Objective() (_swig_ret Objective) {
	var swig_r Objective
	_swig_i_0 := arg1
	swig_r = (Objective)(SwigcptrObjective(C._wrap_Solver_Objective_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))))
	return swig_r
}

type Operations_researchMPSolverResultStatus int

func _swig_getSolver_OPTIMAL_Solver() (_swig_ret Operations_researchMPSolverResultStatus) {
	var swig_r Operations_researchMPSolverResultStatus
	swig_r = (Operations_researchMPSolverResultStatus)(C._wrap_OPTIMAL_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverOPTIMAL Operations_researchMPSolverResultStatus = _swig_getSolver_OPTIMAL_Solver()

func _swig_getSolver_FEASIBLE_Solver() (_swig_ret Operations_researchMPSolverResultStatus) {
	var swig_r Operations_researchMPSolverResultStatus
	swig_r = (Operations_researchMPSolverResultStatus)(C._wrap_FEASIBLE_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverFEASIBLE Operations_researchMPSolverResultStatus = _swig_getSolver_FEASIBLE_Solver()

func _swig_getSolver_INFEASIBLE_Solver() (_swig_ret Operations_researchMPSolverResultStatus) {
	var swig_r Operations_researchMPSolverResultStatus
	swig_r = (Operations_researchMPSolverResultStatus)(C._wrap_INFEASIBLE_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverINFEASIBLE Operations_researchMPSolverResultStatus = _swig_getSolver_INFEASIBLE_Solver()

func _swig_getSolver_UNBOUNDED_Solver() (_swig_ret Operations_researchMPSolverResultStatus) {
	var swig_r Operations_researchMPSolverResultStatus
	swig_r = (Operations_researchMPSolverResultStatus)(C._wrap_UNBOUNDED_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverUNBOUNDED Operations_researchMPSolverResultStatus = _swig_getSolver_UNBOUNDED_Solver()

func _swig_getSolver_ABNORMAL_Solver() (_swig_ret Operations_researchMPSolverResultStatus) {
	var swig_r Operations_researchMPSolverResultStatus
	swig_r = (Operations_researchMPSolverResultStatus)(C._wrap_ABNORMAL_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverABNORMAL Operations_researchMPSolverResultStatus = _swig_getSolver_ABNORMAL_Solver()

func _swig_getSolver_NOT_SOLVED_Solver() (_swig_ret Operations_researchMPSolverResultStatus) {
	var swig_r Operations_researchMPSolverResultStatus
	swig_r = (Operations_researchMPSolverResultStatus)(C._wrap_NOT_SOLVED_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverNOT_SOLVED Operations_researchMPSolverResultStatus = _swig_getSolver_NOT_SOLVED_Solver()

func (arg1 SwigcptrSolver) Solve__SWIG_0() (_swig_ret Operations_researchMPSolverResultStatus) {
	var swig_r Operations_researchMPSolverResultStatus
	_swig_i_0 := arg1
	swig_r = (Operations_researchMPSolverResultStatus)(C._wrap_Solver_Solve__SWIG_0_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSolver) Solve__SWIG_1(arg2 MPSolverParameters) (_swig_ret Operations_researchMPSolverResultStatus) {
	var swig_r Operations_researchMPSolverResultStatus
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Operations_researchMPSolverResultStatus)(C._wrap_Solver_Solve__SWIG_1_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (p SwigcptrSolver) Solve(a ...interface{}) Operations_researchMPSolverResultStatus {
	argc := len(a)
	if argc == 0 {
		return p.Solve__SWIG_0()
	}
	if argc == 1 {
		return p.Solve__SWIG_1(a[0].(MPSolverParameters))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrSolver) ComputeConstraintActivities() (_swig_ret Std_vector_Sl_double_Sg_) {
	var swig_r Std_vector_Sl_double_Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_double_Sg_)(SwigcptrStd_vector_Sl_double_Sg_(C._wrap_Solver_ComputeConstraintActivities_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSolver) VerifySolution(arg2 float64, arg3 bool) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (bool)(C._wrap_Solver_VerifySolution_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C._Bool(_swig_i_2)))
	return swig_r
}

func (arg1 SwigcptrSolver) InterruptSolve() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Solver_InterruptSolve_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSolver) SetSolverSpecificParametersAsString(arg2 Std_string) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (bool)(C._wrap_Solver_SetSolverSpecificParametersAsString_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

type Operations_researchMPSolverBasisStatus int

func _swig_getSolver_FREE_Solver() (_swig_ret Operations_researchMPSolverBasisStatus) {
	var swig_r Operations_researchMPSolverBasisStatus
	swig_r = (Operations_researchMPSolverBasisStatus)(C._wrap_FREE_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverFREE Operations_researchMPSolverBasisStatus = _swig_getSolver_FREE_Solver()

func _swig_getSolver_AT_LOWER_BOUND_Solver() (_swig_ret Operations_researchMPSolverBasisStatus) {
	var swig_r Operations_researchMPSolverBasisStatus
	swig_r = (Operations_researchMPSolverBasisStatus)(C._wrap_AT_LOWER_BOUND_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverAT_LOWER_BOUND Operations_researchMPSolverBasisStatus = _swig_getSolver_AT_LOWER_BOUND_Solver()

func _swig_getSolver_AT_UPPER_BOUND_Solver() (_swig_ret Operations_researchMPSolverBasisStatus) {
	var swig_r Operations_researchMPSolverBasisStatus
	swig_r = (Operations_researchMPSolverBasisStatus)(C._wrap_AT_UPPER_BOUND_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverAT_UPPER_BOUND Operations_researchMPSolverBasisStatus = _swig_getSolver_AT_UPPER_BOUND_Solver()

func _swig_getSolver_FIXED_VALUE_Solver() (_swig_ret Operations_researchMPSolverBasisStatus) {
	var swig_r Operations_researchMPSolverBasisStatus
	swig_r = (Operations_researchMPSolverBasisStatus)(C._wrap_FIXED_VALUE_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverFIXED_VALUE Operations_researchMPSolverBasisStatus = _swig_getSolver_FIXED_VALUE_Solver()

func _swig_getSolver_BASIC_Solver() (_swig_ret Operations_researchMPSolverBasisStatus) {
	var swig_r Operations_researchMPSolverBasisStatus
	swig_r = (Operations_researchMPSolverBasisStatus)(C._wrap_BASIC_Solver_ilp_70c2f4f52bc62623())
	return swig_r
}

var SolverBASIC Operations_researchMPSolverBasisStatus = _swig_getSolver_BASIC_Solver()

func SolverInfinity() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_Solver_infinity_ilp_70c2f4f52bc62623())
	return swig_r
}

func (arg1 SwigcptrSolver) EnableOutput() {
	_swig_i_0 := arg1
	C._wrap_Solver_EnableOutput_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrSolver) SuppressOutput() {
	_swig_i_0 := arg1
	C._wrap_Solver_SuppressOutput_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrSolver) Set_time_limit(arg2 Int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Solver_set_time_limit_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrSolver) Wall_time() (_swig_ret Int64) {
	var swig_r Int64
	_swig_i_0 := arg1
	swig_r = (Int64)(SwigcptrInt64(C._wrap_Solver_wall_time_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSolver) Iterations() (_swig_ret Int64) {
	var swig_r Int64
	_swig_i_0 := arg1
	swig_r = (Int64)(SwigcptrInt64(C._wrap_Solver_iterations_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSolver) Nodes() (_swig_ret Int64) {
	var swig_r Int64
	_swig_i_0 := arg1
	swig_r = (Int64)(SwigcptrInt64(C._wrap_Solver_nodes_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSolver) ComputeExactConditionNumber() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Solver_ComputeExactConditionNumber_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSolver) ExportModelAsLpFormat(arg2 bool) (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_Solver_ExportModelAsLpFormat_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrSolver) ExportModelAsMpsFormat(arg2 bool, arg3 bool) (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_Solver_ExportModelAsMpsFormat_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1), C._Bool(_swig_i_2))))
	return swig_r
}

func (arg1 SwigcptrSolver) LoadModelFromProto(arg2 Operations_research_MPModelProto) (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_Solver_LoadModelFromProto_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrSolver) SetTimeLimit(arg2 Int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Solver_SetTimeLimit_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrSolver) WallTime() (_swig_ret Int64) {
	var swig_r Int64
	_swig_i_0 := arg1
	swig_r = (Int64)(SwigcptrInt64(C._wrap_Solver_WallTime_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))))
	return swig_r
}

type Solver interface {
	Swigcptr() uintptr
	SwigIsSolver()
	Clear()
	NumVariables() (_swig_ret int)
	LookupVariable(arg2 Std_string) (_swig_ret Variable)
	NumVar(arg2 float64, arg3 float64, arg4 Std_string) (_swig_ret Variable)
	IntVar(arg2 float64, arg3 float64, arg4 Std_string) (_swig_ret Variable)
	BoolVar(arg2 Std_string) (_swig_ret Variable)
	NumConstraints() (_swig_ret int)
	LookupConstraint(arg2 Std_string) (_swig_ret Constraint)
	Constraint(a ...interface{}) Constraint
	Objective() (_swig_ret Objective)
	Solve(a ...interface{}) Operations_researchMPSolverResultStatus
	ComputeConstraintActivities() (_swig_ret Std_vector_Sl_double_Sg_)
	VerifySolution(arg2 float64, arg3 bool) (_swig_ret bool)
	InterruptSolve() (_swig_ret bool)
	SetSolverSpecificParametersAsString(arg2 Std_string) (_swig_ret bool)
	EnableOutput()
	SuppressOutput()
	Set_time_limit(arg2 Int64)
	Wall_time() (_swig_ret Int64)
	Iterations() (_swig_ret Int64)
	Nodes() (_swig_ret Int64)
	ComputeExactConditionNumber() (_swig_ret float64)
	ExportModelAsLpFormat(arg2 bool) (_swig_ret Std_string)
	ExportModelAsMpsFormat(arg2 bool, arg3 bool) (_swig_ret Std_string)
	LoadModelFromProto(arg2 Operations_research_MPModelProto) (_swig_ret Std_string)
	SetTimeLimit(arg2 Int64)
	WallTime() (_swig_ret Int64)
}

type SwigcptrObjective uintptr

func (p SwigcptrObjective) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrObjective) SwigIsObjective() {
}

func (arg1 SwigcptrObjective) Clear() {
	_swig_i_0 := arg1
	C._wrap_Objective_Clear_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrObjective) SetCoefficient(arg2 Variable, arg3 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_Objective_SetCoefficient_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.double(_swig_i_2))
}

func (arg1 SwigcptrObjective) GetCoefficient(arg2 Variable) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (float64)(C._wrap_Objective_GetCoefficient_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrObjective) SetOffset(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Objective_SetOffset_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrObjective) Offset() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Objective_offset_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrObjective) AddOffset(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Objective_AddOffset_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrObjective) SetOptimizationDirection(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Objective_SetOptimizationDirection_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrObjective) SetMinimization() {
	_swig_i_0 := arg1
	C._wrap_Objective_SetMinimization_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrObjective) SetMaximization() {
	_swig_i_0 := arg1
	C._wrap_Objective_SetMaximization_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrObjective) Maximization() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Objective_maximization_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrObjective) Minimization() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Objective_minimization_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrObjective) Value() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Objective_Value_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrObjective) BestBound() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Objective_BestBound_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteObjective(arg1 Objective) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Objective_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

type Objective interface {
	Swigcptr() uintptr
	SwigIsObjective()
	Clear()
	SetCoefficient(arg2 Variable, arg3 float64)
	GetCoefficient(arg2 Variable) (_swig_ret float64)
	SetOffset(arg2 float64)
	Offset() (_swig_ret float64)
	AddOffset(arg2 float64)
	SetOptimizationDirection(arg2 bool)
	SetMinimization()
	SetMaximization()
	Maximization() (_swig_ret bool)
	Minimization() (_swig_ret bool)
	Value() (_swig_ret float64)
	BestBound() (_swig_ret float64)
}

type SwigcptrVariable uintptr

func (p SwigcptrVariable) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVariable) SwigIsVariable() {
}

func (arg1 SwigcptrVariable) Name() (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_Variable_name_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVariable) Integer() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Variable_integer_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVariable) Solution_value() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Variable_solution_value_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVariable) Index() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Variable_index_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVariable) Lb() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Variable_lb_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVariable) Ub() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Variable_ub_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVariable) Reduced_cost() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Variable_reduced_cost_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVariable) Basis_status() (_swig_ret Operations_researchMPSolverBasisStatus) {
	var swig_r Operations_researchMPSolverBasisStatus
	_swig_i_0 := arg1
	swig_r = (Operations_researchMPSolverBasisStatus)(C._wrap_Variable_basis_status_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVariable) X__str__() (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_Variable___str___ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVariable) X__repr__() (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_Variable___repr___ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVariable) SolutionValue() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Variable_SolutionValue_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVariable) SetLb(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Variable_SetLb_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrVariable) SetUb(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Variable_SetUb_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrVariable) ReducedCost() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Variable_ReducedCost_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteVariable(arg1 Variable) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Variable_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

type Variable interface {
	Swigcptr() uintptr
	SwigIsVariable()
	Name() (_swig_ret Std_string)
	Integer() (_swig_ret bool)
	Solution_value() (_swig_ret float64)
	Index() (_swig_ret int)
	Lb() (_swig_ret float64)
	Ub() (_swig_ret float64)
	Reduced_cost() (_swig_ret float64)
	Basis_status() (_swig_ret Operations_researchMPSolverBasisStatus)
	X__str__() (_swig_ret Std_string)
	X__repr__() (_swig_ret Std_string)
	SolutionValue() (_swig_ret float64)
	SetLb(arg2 float64)
	SetUb(arg2 float64)
	ReducedCost() (_swig_ret float64)
}

type SwigcptrConstraint uintptr

func (p SwigcptrConstraint) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrConstraint) SwigIsConstraint() {
}

func (arg1 SwigcptrConstraint) Name() (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_Constraint_name_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrConstraint) SetCoefficient(arg2 Variable, arg3 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_Constraint_SetCoefficient_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.double(_swig_i_2))
}

func (arg1 SwigcptrConstraint) GetCoefficient(arg2 Variable) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (float64)(C._wrap_Constraint_GetCoefficient_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrConstraint) Lb() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Constraint_lb_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrConstraint) Ub() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Constraint_ub_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrConstraint) SetLB(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Constraint_SetLB_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrConstraint) SetUB(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Constraint_SetUB_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrConstraint) SetBounds(arg2 float64, arg3 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Constraint_SetBounds_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2))
}

func (arg1 SwigcptrConstraint) Set_is_lazy(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Constraint_set_is_lazy_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrConstraint) Index() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Constraint_index_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrConstraint) Dual_value() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Constraint_dual_value_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrConstraint) Basis_status() (_swig_ret Operations_researchMPSolverBasisStatus) {
	var swig_r Operations_researchMPSolverBasisStatus
	_swig_i_0 := arg1
	swig_r = (Operations_researchMPSolverBasisStatus)(C._wrap_Constraint_basis_status_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrConstraint) SetLb(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Constraint_SetLb_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrConstraint) SetUb(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Constraint_SetUb_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrConstraint) DualValue() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Constraint_DualValue_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteConstraint(arg1 Constraint) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Constraint_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

type Constraint interface {
	Swigcptr() uintptr
	SwigIsConstraint()
	Name() (_swig_ret Std_string)
	SetCoefficient(arg2 Variable, arg3 float64)
	GetCoefficient(arg2 Variable) (_swig_ret float64)
	Lb() (_swig_ret float64)
	Ub() (_swig_ret float64)
	SetLB(arg2 float64)
	SetUB(arg2 float64)
	SetBounds(arg2 float64, arg3 float64)
	Set_is_lazy(arg2 bool)
	Index() (_swig_ret int)
	Dual_value() (_swig_ret float64)
	Basis_status() (_swig_ret Operations_researchMPSolverBasisStatus)
	SetLb(arg2 float64)
	SetUb(arg2 float64)
	DualValue() (_swig_ret float64)
}

type SwigcptrMPSolverParameters uintptr

func (p SwigcptrMPSolverParameters) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrMPSolverParameters) SwigIsMPSolverParameters() {
}

type Operations_researchMPSolverParametersDoubleParam int

func _swig_getMPSolverParameters_RELATIVE_MIP_GAP_MPSolverParameters() (_swig_ret Operations_researchMPSolverParametersDoubleParam) {
	var swig_r Operations_researchMPSolverParametersDoubleParam
	swig_r = (Operations_researchMPSolverParametersDoubleParam)(C._wrap_RELATIVE_MIP_GAP_MPSolverParameters_ilp_70c2f4f52bc62623())
	return swig_r
}

var MPSolverParametersRELATIVE_MIP_GAP Operations_researchMPSolverParametersDoubleParam = _swig_getMPSolverParameters_RELATIVE_MIP_GAP_MPSolverParameters()

type Operations_researchMPSolverParametersIntegerParam int

func _swig_getMPSolverParameters_PRESOLVE_MPSolverParameters() (_swig_ret Operations_researchMPSolverParametersIntegerParam) {
	var swig_r Operations_researchMPSolverParametersIntegerParam
	swig_r = (Operations_researchMPSolverParametersIntegerParam)(C._wrap_PRESOLVE_MPSolverParameters_ilp_70c2f4f52bc62623())
	return swig_r
}

var MPSolverParametersPRESOLVE Operations_researchMPSolverParametersIntegerParam = _swig_getMPSolverParameters_PRESOLVE_MPSolverParameters()

func GetMPSolverParametersKDefaultPrimalTolerance() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_MPSolverParameters_kDefaultPrimalTolerance_get_ilp_70c2f4f52bc62623())
	return swig_r
}

func NewMPSolverParameters() (_swig_ret MPSolverParameters) {
	var swig_r MPSolverParameters
	swig_r = (MPSolverParameters)(SwigcptrMPSolverParameters(C._wrap_new_MPSolverParameters_ilp_70c2f4f52bc62623()))
	return swig_r
}

func (arg1 SwigcptrMPSolverParameters) SetDoubleParam(arg2 Operations_researchMPSolverParametersDoubleParam, arg3 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_MPSolverParameters_SetDoubleParam_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.double(_swig_i_2))
}

func (arg1 SwigcptrMPSolverParameters) SetIntegerParam(arg2 Operations_researchMPSolverParametersIntegerParam, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_MPSolverParameters_SetIntegerParam_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func (arg1 SwigcptrMPSolverParameters) GetDoubleParam(arg2 Operations_researchMPSolverParametersDoubleParam) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_MPSolverParameters_GetDoubleParam_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrMPSolverParameters) GetIntegerParam(arg2 Operations_researchMPSolverParametersIntegerParam) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_MPSolverParameters_GetIntegerParam_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func DeleteMPSolverParameters(arg1 MPSolverParameters) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_MPSolverParameters_ilp_70c2f4f52bc62623(C.uintptr_t(_swig_i_0))
}

type MPSolverParameters interface {
	Swigcptr() uintptr
	SwigIsMPSolverParameters()
	SetDoubleParam(arg2 Operations_researchMPSolverParametersDoubleParam, arg3 float64)
	SetIntegerParam(arg2 Operations_researchMPSolverParametersIntegerParam, arg3 int)
	GetDoubleParam(arg2 Operations_researchMPSolverParametersDoubleParam) (_swig_ret float64)
	GetIntegerParam(arg2 Operations_researchMPSolverParametersIntegerParam) (_swig_ret int)
}

type SwigcptrInt64 uintptr
type Int64 interface {
	Swigcptr() uintptr
}

func (p SwigcptrInt64) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrOperations_research_MPModelProto uintptr
type Operations_research_MPModelProto interface {
	Swigcptr() uintptr
}

func (p SwigcptrOperations_research_MPModelProto) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_double_Sg_ uintptr
type Std_vector_Sl_double_Sg_ interface {
	Swigcptr() uintptr
}

func (p SwigcptrStd_vector_Sl_double_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_string uintptr
type Std_string interface {
	Swigcptr() uintptr
}

func (p SwigcptrStd_string) Swigcptr() uintptr {
	return uintptr(p)
}
